package ch03

import ch03.List_.{ Empty, Pair }

class ListSuite extends munit.FunSuite {
  test("isEmpty should return true for an empty list") {
    val obtained = Empty[Int]()
    assert(obtained.isEmpty)
  }

  test("isEmpty should return false for a non-empty list") {
    val obtained = Pair(1, Empty[Int]())
    assert(!obtained.isEmpty)
  }

  test("headOpt should return None for an empty list") {
    val obtained = Empty[Int]()
    assertEquals(obtained.headOpt, None)
  }

  test("headOpt should return Some(head) for a non-empty list") {
    val obtained = Pair(1, Empty[Int]())
    assertEquals(obtained.headOpt, Some(1))
  }

  test("tail should return an empty list for an empty list") {
    val obtained = Empty[Int]()
    assertEquals(obtained.tail, Empty[Int]())
  }

  test("tail should return the tail of a non-empty list") {
    val obtained = Pair(1, Pair(2, Empty[Int]()))
    val expected = Pair(2, Empty[Int]())
    assertEquals(obtained.tail, expected)
  }

  test("map should transform the values in the list") {
    val obtained = Pair(1, Pair(2, Empty[Int]()))
    val expected = Pair("1", Pair("2", Empty[String]()))
    assertEquals(obtained.map(_.toString), expected)
  }

  test("unfold should generate a list from a seed value") {
    val obtained = List_.unfold(0)(_ >= 5, identity, _ + 1)
    val expected = Pair(0, Pair(1, Pair(2, Pair(3, Pair(4, Empty[Int]())))))
    assertEquals(obtained, expected)
  }

  test("unfold should return an empty list if the stop condition is met immediately") {
    val obtained = List_.unfold(0)(_ >= 0, identity, _ + 1)
    val expected = Empty[Int]()
    assertEquals(obtained, expected)
  }
  
  test("fill should create a list of the specified length with the given element") {
    val obtained = List_.fill(3)("a")
    val expected = Pair("a", Pair("a", Pair("a", Empty[String]())))
    assertEquals(obtained, expected)
  }
  
  test("fill should return an empty list if n is zero") {
    val obtained = List_.fill(0)("a")
    val expected = Empty[String]()
    assertEquals(obtained, expected)
  }
  
  test("iterate should create a list of values generated by applying f") {
    val obtained = List_.iterate(1, 5)(_ * 2)
    val expected = Pair(1, Pair(2, Pair(4, Pair(8, Pair(16, Empty())))))
    assertEquals(obtained, expected)
  }
}
